### ISSUE TITLE
code: 2, kind: NotFound, message: "No such file or directory"

### ISSUE THREAD

**Issue by csxuyang** [kaedon78/ore-cli-mod#1]
Hi,bro:
 I just run the program,but is error . the commad:
  ore \
                --rpc  XXX  \
                --keypair1 /root/.config/solana/id0.json \
                --priority-fee 1 \
                mine 

the error below:
thread 'main' panicked at src/main.rs:333:59:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Thank you for sharing!

**Comment by ddb136183** [comment]
Yes, same as the one above, when I try to run, I have the same error, when defining the "--keypair1" path


root@XXXX:~/ore-cli-mod# ./target/release/ore --rpc XX --keypair1 ~/.config/solana/id.json --priority-fee X mine
URL https://xxxxxx/
Registration OK...
thread 'main' panicked at src/main.rs:333:59:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Thank you for your sharing and time.bro
full of respect for you

**Comment by kaedon78** [comment]
you need to provide 5 keypairs total for it to work

**Comment by sa0201** [comment]
可以提供一个样例吗?
ore --rpc xxxx --keypair1 ~/.config/solana/id.json --keypair2 ~/.config/solana/id1.json --keypair3 ~/.config/solana/id2.json --keypair4 ~/.config/solana/id3.json --keypair5 ~/.config/solana/id7.json --priority-fee 20000  mine --threads 4

**Comment by kaedon78** [comment]
Beta branch now allows variable number of keys from 1 to 5 through params --keypair1, --keypair2, --keypair3, --keypair4, --keypair5.
