### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by 0xkaka** [kaedon78/ore-cli-mod#3]
It seems that there is a very expensive packaging fee, and the GAS does not match what I have set up

**Comment by BankkRoll** [comment]
Take a look at the code, fees is auto adjusted..

**Comment by 0xkaka** [comment]
> 看一下代码，费用是自动调整的。

Hello sir, I am a beginner. I have built it and it can run normally, but the package is too large, over 1GB. How can I put it on my server

**Comment by kaedon78** [comment]
Auto-adjustment logic removed, switched back to original logic to set priority fee from command line param value.
