### ISSUE TITLE
Can you add GPU mode, sir? 

### ISSUE THREAD

**Issue by 0xkaka** [kaedon78/ore-cli-mod#4]
Can you add GPU mode, sir? There is currently GPU open source, but Jito cannot be removed. Can you take a look and make optimizations?
https://github.com/tonyke-bot/ore-miner

**Comment by kaedon78** [comment]
working on it

**Comment by kaedon78** [comment]
See beta branch for working GPU support for v1.  However, with v1 mining stopped, this won't be usable for ORE until v2 comes out and the hashing code is updated per v2 requirements.
